# Generated by Django 5.2.12 on 2026-06-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monjuriste', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avocatprofile',
            name='photo',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
