# Generated by Django 5.2.12 on 2026-06-04 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monjuriste', '0003_conversation_message_messagefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('AUDIO', 'Audio'), ('VIDEO', 'Vidéo')], max_length=10)),
                ('status', models.CharField(choices=[('REQUESTED', 'Demandé'), ('ONGOING', 'En cours'), ('ENDED', 'Terminé'), ('MISSED', 'Manqué')], default='REQUESTED', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='monjuriste.conversation')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appel',
                'verbose_name_plural': 'Appels',
                'ordering': ['-started_at'],
            },
        ),
    ]
