# Generated by Django 5.2.12 on 2026-06-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monjuriste', '0004_conversationcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='avocatprofile',
            name='annees_experience',
            field=models.PositiveIntegerField(default=0, verbose_name="Années d'expérience"),
        ),
        migrations.AddField(
            model_name='avocatprofile',
            name='cabinet',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cabinet / Étude'),
        ),
        migrations.AddField(
            model_name='avocatprofile',
            name='ville',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
    ]
